DEVICE: cpu                             # device used for training
SAVE_DIR: './output'                    # output folder name used for saving the trained model and logs
MODEL_PATH: './output/mixer_B.pth'      # trained model path (used for evaluation, inference and optimization)

MODEL:
  NAME: 'resnet'                         # name of the model you are using
  VARIANT: '18'                          # sub name of the model you are using 

DATASET:
  NAME: esc50                        # dataset name
  ROOT: 'data/ESC50'          # dataset root path
  AUG: true                             # augment the audio dataset or not
  NUM_CLASSES: 50

TRAIN:
  FOLD: 1                               # which fold to train
  EPOCHS: 100                           # number of epochs to train
  BATCH_SIZE: 16                         # batch size used to train
  WORKERS: 8                            # number of workers used in training dataloader
  LOSS: label_smooth                    # loss function name (vanilla, label_smooth, soft_target)
  OPTIMIZER:
    NAME: adamw
    LR: 0.0001                              # initial learning rate used in optimizer
    WEIGHT_DECAY: 0.001                    # decay rate use in optimizer
  SCHEDULER:
    NAME: steplr
    PARAMS: (30, 0.1)
  EVAL_INTERVAL: 20                     # interval to evaluate the model during training
  AMP: false                            # use Automatic Mixed Precision training or not
  DDP: 
    ENABLE: false                       # use ddp training
    REPEATED_AUG: true                  # each gpu will see different augmented version of same images

EVAL:
  IMAGE_SIZE: [224, 224]                # evaluation image size
  BATCH_SIZE: 8                         # evaluation batch size
  WORKERS: 4                            # number of workers used in evalaution dataloader
  
TEST:
  MODE: image                           # inference mode (image)
  FILE: 'assests/dog.jpg'               # filename or foldername (image mode)
  IMAGE_SIZE: [224, 224]                # inference image size

KD:
  ENABLE: false                         # train with knowledge distillation
  METHOD: vanilla                       # knowledge distillation method
  TEACHER:                                    
    NAME: mixer                         # teacher model name
    VARIANT: L                          # teacher model sub-name
    PRETRAINED: 'mixer_L.pth'           # teacher model weights path
  ALPHA: 0.95                           # [0.99, 0.95, 0.5, 0.1, 0.05]
  TEMP: 6                               # [20, 10, 8, 6, 4.5, 3, 2, 1.5]