DEVICE: cpu                             # device used for training
SAVE_DIR: './output'                    # output folder name used for saving the trained model and logs
MODEL_PATH: 'checkpoints/cnn14.pth'      # trained model path (used for evaluation, inference and optimization)

SAMPLE_RATE: 32000
WIN_LENGTH: 1024
N_MELS: 64
FMIN: 50
FMAX: 14000

MODEL:
  NAME: 'cnn14'                         # name of the model you are using
  PRETRAINED: 'checkpoints/cnn14.pth'

DATASET:
  NAME: audioset                        # dataset name
  ROOT: 'data/ESC50'                    # dataset root path
  AUG: true                             # augment the audio dataset or not

TRAIN:
  EPOCHS: 100                           # number of epochs to train
  BATCH_SIZE: 16                         # batch size used to train
  WORKERS: 8                            # number of workers used in training dataloader
  LOSS: bce                    # loss function name (ce, bce, label_smooth, soft_target)
  OPTIMIZER:
    NAME: adamw
    LR: 0.0001                              # initial learning rate used in optimizer
    WEIGHT_DECAY: 0.001                    # decay rate use in optimizer
  SCHEDULER:
    NAME: steplr
    PARAMS: (30, 0.1)
  EVAL_INTERVAL: 20                     # interval to evaluate the model during training
  AMP: false                            # use Automatic Mixed Precision training or not
  DDP: false

EVAL:
  BATCH_SIZE: 8                         # evaluation batch size
  WORKERS: 4                            # number of workers used in evalaution dataloader
  
TEST:
  MODE: file                           # inference mode (file, mic)
  FILE: 'assests/test.wav'               # filename or foldername (image mode)
  TOPK: 5